---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Apply Updates (CentOS)
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == 'CentOS'

    - name: Apply Updates (CentOS)
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - include: tasks/user.yml
    - include: tasks/docker.yml
    - include: tasks/kubectl.yml
    - include: tasks/minikube.yml
