- name: Installing Docker Repo
  command: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == 'CentOS'

- name: Installing Docker
  command: sudo dnf install docker -y
  when: ansible_distribution == 'CentOS'

- name: Install Docker (Ubuntu)
  become: true
  become_user: ubuntu
  shell: 
    sudo apt install apt-transport-https ca-certificates curl software-properties-common && 
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" &&
    apt-cache policy docker-ce &&
    sudo apt install docker-ce
  when: ansible_distribution == 'Ubuntu'

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: True
