- name: Installing Docker Repo
  command: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo 

- name: Installing Docker
  command: sudo dnf install docker -y
  

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: True
  
  
