- name: Installing Docker Repo
  command: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == 'CentOS'

- name: Installing Docker
  command: sudo dnf install docker -y
  when: ansible_distribution == 'CentOS'

- name: Install Docker (Ubuntu)
  apt:
    name: docker
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: True
