- name: Installing Minikube Repo
  command: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  when: ansible_distribution == 'CentOS'

- name: Installing Minikube
  command: sudo install minikube-linux-amd64 /usr/local/bin/minikube
  when: ansible_distribution == 'CentOS'

- name: Installing Minikube
  loop:
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - sudo mkdir -p /usr/local/bin/
    - sudo install minikube /usr/local/bin/
    - sudo chmod 755 /usr/local/bin/minikube
  when: ansible_distribution == 'Ubuntu'
